/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmpCredits {
        "name": string;
    }
    interface EmpItem {
        "label": string;
        "pos": string;
    }
    interface SideMenu {
        "avatar": string;
        "menu": string;
    }
}
declare global {
    interface HTMLEmpCreditsElement extends Components.EmpCredits, HTMLStencilElement {
    }
    var HTMLEmpCreditsElement: {
        prototype: HTMLEmpCreditsElement;
        new (): HTMLEmpCreditsElement;
    };
    interface HTMLEmpItemElement extends Components.EmpItem, HTMLStencilElement {
    }
    var HTMLEmpItemElement: {
        prototype: HTMLEmpItemElement;
        new (): HTMLEmpItemElement;
    };
    interface HTMLSideMenuElement extends Components.SideMenu, HTMLStencilElement {
    }
    var HTMLSideMenuElement: {
        prototype: HTMLSideMenuElement;
        new (): HTMLSideMenuElement;
    };
    interface HTMLElementTagNameMap {
        "emp-credits": HTMLEmpCreditsElement;
        "emp-item": HTMLEmpItemElement;
        "side-menu": HTMLSideMenuElement;
    }
}
declare namespace LocalJSX {
    interface EmpCredits {
        "name"?: string;
    }
    interface EmpItem {
        "label"?: string;
        "pos"?: string;
    }
    interface SideMenu {
        "avatar"?: string;
        "menu"?: string;
    }
    interface IntrinsicElements {
        "emp-credits": EmpCredits;
        "emp-item": EmpItem;
        "side-menu": SideMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emp-credits": LocalJSX.EmpCredits & JSXBase.HTMLAttributes<HTMLEmpCreditsElement>;
            "emp-item": LocalJSX.EmpItem & JSXBase.HTMLAttributes<HTMLEmpItemElement>;
            "side-menu": LocalJSX.SideMenu & JSXBase.HTMLAttributes<HTMLSideMenuElement>;
        }
    }
}
